KEYBOARD := trackzeron

# MCU name
MCU = at90usb1286

# Processor frequency
F_CPU = 16000000

# Bootloader selection
BOOTLOADER = halfkay
BOOTLOADER_SIZE = 4096

# Build Options
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
MOUSEKEY_ENABLE = yes

RGBLIGHT_ENABLE = no
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
COMMAND_ENABLE = no
